sense:
  ros__parameters:
    # Board dimensions in cells
    board_width_cells: 4
    board_height_cells: 5

    min_cell_colour_area: 500 # Minimum area in pixels for a cell's color to be considered valid

    # Camera frame IDs
    camera_frame_id: "camera_color_optical_frame"
    camera_link_frame_id: "camera_link"

    # Board reference marker config
    #   TL ------ TR
    #    |        |
    #    |        |
    #   BL ------ BR
    #
    board_tl_marker_id: 0 # ID of the top-left corner marker on the board
    board_tr_marker_id: 1 # ID of the top-right corner marker on the board
    board_bl_marker_id: 2 # ID of the bottom-left corner marker on the board
    board_br_marker_id: 3 # ID of the bottom-right corner marker on the board
    marker_length_m: 0.065 # marker side length in meters

    # Board offset and frame ID
    board_offset_x_m: 0.040 # 40mm right (marker frame X)
    board_offset_y_m: 0.040 # 40mm up (marker frame Y)
    board_frame_id: "klotski_board" # board frame ID (offset from bottom-left marker)

    board_piece_counts:
      red: 1
      green: 1
      blue: 4
      yellow: 4
      empty: 2

    world_frame_id: "base_link"

    hsv_config_file: "hsv_ranges.default.yaml" # omitted path is relative to src/pkg_sense/config/

